# Default configuration for ReqNinja
# Copy this to ~/.reqninja/config.yml and customize as needed

# Global settings
default_retries: 3
default_timeout: 30
default_headers:
  User-Agent: ReqNinja/1.0
  Content-Type: application/json

# Retry policy configuration
retry_policy:
  total: 3
  status_forcelist: [429, 500, 502, 503, 504]
  backoff_factor: 0.5
  max_backoff: 120

# Environment profiles
profiles:
  
  # Development environment
  dev:
    base_url: http://localhost:8000
    headers:
      Authorization: Bearer dev-token
    timeout: 10
  
  # Staging environment  
  staging:
    base_url: https://staging-api.example.com
    headers:
      Authorization: Bearer ${STAGING_TOKEN}
    timeout: 30
    
  # Production environment
  prod:
    base_url: https://api.example.com
    headers:
      Authorization: Bearer ${PROD_TOKEN}
    timeout: 30
    retry_policy:
      total: 5
      backoff_factor: 1.0

# Example with different auth methods
  api_key_example:
    base_url: https://api.service.com
    auth:
      type: api_key
      key: ${API_KEY}
      header: X-API-Key
      
  basic_auth_example:
    base_url: https://api.legacy.com
    auth:
      type: basic
      username: ${USERNAME}
      password: ${PASSWORD}
